//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetLoginOff
    {
        public long LoginLogoutID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Login { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<short> BranchID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
