//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Holidays
    {
        public int BnchComHolyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> HolidayTypeID { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public string HolidayName { get; set; }
    
        public virtual Branch_Details Branch_Details { get; set; }
        public virtual Resource_Holiday_Type Resource_Holiday_Type { get; set; }
    }
}
