//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch_Details()
        {
            this.Branch_Holidays = new HashSet<Branch_Holidays>();
            this.Resource_BranchDetails = new HashSet<Resource_BranchDetails>();
            this.Resource_ShiftSchedule = new HashSet<Resource_ShiftSchedule>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public int BranchStatusID { get; set; }
        public int BranchTypeID { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public int AddressID { get; set; }
        public string VATNumber { get; set; }
        public bool Status { get; set; }
    
        public virtual Branch_Status Branch_Status { get; set; }
        public virtual Branch_Type Branch_Type { get; set; }
        public virtual Common_Address Common_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch_Holidays> Branch_Holidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_BranchDetails> Resource_BranchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_ShiftSchedule> Resource_ShiftSchedule { get; set; }
    }
}
