//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Key
    {
        public string KeyName { get; set; }
        public long KeyValue { get; set; }
        public string Prefix { get; set; }
        public string LeadingChar { get; set; }
        public byte MaximumChars { get; set; }
    }
}
