//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_SkillGroup
    {
        public int SkillGroupID { get; set; }
        public Nullable<int> SkillID { get; set; }
        public Nullable<int> SkillCategoryID { get; set; }
        public Nullable<int> SkillLevelID { get; set; }
    
        public virtual Common_Skill Common_Skill { get; set; }
        public virtual Common_SkillCategory Common_SkillCategory { get; set; }
        public virtual Common_SkillLevelScheme Common_SkillLevelScheme { get; set; }
    }
}
