//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_EmployeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common_EmployeeType()
        {
            this.Common_EmployeeType1 = new HashSet<Common_EmployeeType>();
            this.Resource_Employee = new HashSet<Resource_Employee>();
        }
    
        public int EmployeeTypeID { get; set; }
        public string EmployeeTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReportingTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_EmployeeType> Common_EmployeeType1 { get; set; }
        public virtual Common_EmployeeType Common_EmployeeType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_Employee> Resource_Employee { get; set; }
    }
}
