//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_AreaPostCodeDetails
    {
        public int PostCodeID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string PostCode { get; set; }
    
        public virtual Common_Area Common_Area { get; set; }
    }
}
