//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_SkillLevelScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common_SkillLevelScheme()
        {
            this.Common_SkillGroup = new HashSet<Common_SkillGroup>();
        }
    
        public int SkillLevelID { get; set; }
        public string SkillLevelName { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaxSkillLevel { get; set; }
        public Nullable<int> MinSkillLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_SkillGroup> Common_SkillGroup { get; set; }
    }
}
