//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetLoginOff> AspNetLoginOffs { get; set; }
        public virtual DbSet<AspNetPermission> AspNetPermissions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Branch_Details> Branch_Details { get; set; }
        public virtual DbSet<Branch_Holidays> Branch_Holidays { get; set; }
        public virtual DbSet<Branch_Status> Branch_Status { get; set; }
        public virtual DbSet<Branch_Type> Branch_Type { get; set; }
        public virtual DbSet<Common_Address> Common_Address { get; set; }
        public virtual DbSet<Common_Area> Common_Area { get; set; }
        public virtual DbSet<Common_AreaPostCodeDetails> Common_AreaPostCodeDetails { get; set; }
        public virtual DbSet<Common_Company> Common_Company { get; set; }
        public virtual DbSet<Common_Country> Common_Country { get; set; }
        public virtual DbSet<Common_CurrencyFormat> Common_CurrencyFormat { get; set; }
        public virtual DbSet<Common_DateFormat> Common_DateFormat { get; set; }
        public virtual DbSet<Common_Day> Common_Day { get; set; }
        public virtual DbSet<Common_Department> Common_Department { get; set; }
        public virtual DbSet<Common_Designation> Common_Designation { get; set; }
        public virtual DbSet<Common_EmployeeType> Common_EmployeeType { get; set; }
        public virtual DbSet<Common_EthnicGroup> Common_EthnicGroup { get; set; }
        public virtual DbSet<Common_HostLogo> Common_HostLogo { get; set; }
        public virtual DbSet<Common_HostSettings> Common_HostSettings { get; set; }
        public virtual DbSet<Common_ImmigrationStatus> Common_ImmigrationStatus { get; set; }
        public virtual DbSet<Common_JobTitle> Common_JobTitle { get; set; }
        public virtual DbSet<Common_Key> Common_Key { get; set; }
        public virtual DbSet<Common_Location> Common_Location { get; set; }
        public virtual DbSet<Common_MaritalStatus> Common_MaritalStatus { get; set; }
        public virtual DbSet<Common_Nationality> Common_Nationality { get; set; }
        public virtual DbSet<Common_PaymentType> Common_PaymentType { get; set; }
        public virtual DbSet<Common_Region> Common_Region { get; set; }
        public virtual DbSet<Common_Skill> Common_Skill { get; set; }
        public virtual DbSet<Common_SkillCategory> Common_SkillCategory { get; set; }
        public virtual DbSet<Common_SkillGroup> Common_SkillGroup { get; set; }
        public virtual DbSet<Common_SkillLevelScheme> Common_SkillLevelScheme { get; set; }
        public virtual DbSet<Common_Team> Common_Team { get; set; }
        public virtual DbSet<Common_TimeFormat> Common_TimeFormat { get; set; }
        public virtual DbSet<Common_TimeSheetFrequency> Common_TimeSheetFrequency { get; set; }
        public virtual DbSet<Common_Title> Common_Title { get; set; }
        public virtual DbSet<Resouce_WorkingPatternDetails> Resouce_WorkingPatternDetails { get; set; }
        public virtual DbSet<Resource_BranchDetails> Resource_BranchDetails { get; set; }
        public virtual DbSet<Resource_Department> Resource_Department { get; set; }
        public virtual DbSet<Resource_DepartmentAreaDetails> Resource_DepartmentAreaDetails { get; set; }
        public virtual DbSet<Resource_Employee> Resource_Employee { get; set; }
        public virtual DbSet<Resource_EmployeePayment> Resource_EmployeePayment { get; set; }
        public virtual DbSet<Resource_ExperienceDetails> Resource_ExperienceDetails { get; set; }
        public virtual DbSet<Resource_Holiday> Resource_Holiday { get; set; }
        public virtual DbSet<Resource_Holiday_Type> Resource_Holiday_Type { get; set; }
        public virtual DbSet<Resource_HolidayStatus> Resource_HolidayStatus { get; set; }
        public virtual DbSet<Resource_HolidayStatusType> Resource_HolidayStatusType { get; set; }
        public virtual DbSet<Resource_ShiftPattern> Resource_ShiftPattern { get; set; }
        public virtual DbSet<Resource_ShiftSchedule> Resource_ShiftSchedule { get; set; }
        public virtual DbSet<Resource_SkillDetails> Resource_SkillDetails { get; set; }
        public virtual DbSet<Resource_TimeSheet> Resource_TimeSheet { get; set; }
        public virtual DbSet<Resource_TimeSheetDetails> Resource_TimeSheetDetails { get; set; }
        public virtual DbSet<Resource_TimeSheetDetailsHoliday> Resource_TimeSheetDetailsHoliday { get; set; }
        public virtual DbSet<Resource_WeeklyPatternDetails> Resource_WeeklyPatternDetails { get; set; }
        public virtual DbSet<Resource_WorkingPattern> Resource_WorkingPattern { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_UserDetails> User_UserDetails { get; set; }
    }
}
