//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_TimeSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_TimeSheet()
        {
            this.Resource_TimeSheetDetails = new HashSet<Resource_TimeSheetDetails>();
            this.Resource_TimeSheetDetailsHoliday = new HashSet<Resource_TimeSheetDetailsHoliday>();
        }
    
        public int TimeSheetID { get; set; }
        public int ResourceID { get; set; }
        public System.DateTime TimeSheetDate { get; set; }
        public int TimeSheetFrequencyID { get; set; }
        public int NoOfShift { get; set; }
        public double TotalShiftHours { get; set; }
        public double NoOfHolidays { get; set; }
        public double NoOfHolidayHours { get; set; }
        public double Payment { get; set; }
        public Nullable<System.DateTime> TimeSheetAuthorizationDate { get; set; }
        public string Approved { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockedDateTime { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsAct { get; set; }
    
        public virtual Common_TimeSheetFrequency Common_TimeSheetFrequency { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_TimeSheetDetails> Resource_TimeSheetDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_TimeSheetDetailsHoliday> Resource_TimeSheetDetailsHoliday { get; set; }
    }
}
