//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_ExperienceDetails
    {
        public int ExperienceID { get; set; }
        public int ResourceID { get; set; }
        public int DesignationID { get; set; }
        public int CompanyID { get; set; }
        public string Description { get; set; }
        public string ExternalDesignation { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Common_Company Common_Company { get; set; }
        public virtual Common_Designation Common_Designation { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
    }
}
