//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_BranchDetails
    {
        public int ResourceBranchID { get; set; }
        public int BranchID { get; set; }
        public int ResourceID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Branch_Details Branch_Details { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
    }
}
