//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_TimeSheetDetailsHoliday
    {
        public int TimeSheetDetailsHoliID { get; set; }
        public Nullable<int> TimeSheetID { get; set; }
        public Nullable<int> HolidayID { get; set; }
    
        public virtual Resource_Holiday Resource_Holiday { get; set; }
        public virtual Resource_TimeSheet Resource_TimeSheet { get; set; }
    }
}
