//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_Employee()
        {
            this.Resouce_WorkingPatternDetails = new HashSet<Resouce_WorkingPatternDetails>();
            this.Resource_BranchDetails = new HashSet<Resource_BranchDetails>();
            this.Resource_Department = new HashSet<Resource_Department>();
            this.Resource_EmployeePayment = new HashSet<Resource_EmployeePayment>();
            this.Resource_ExperienceDetails = new HashSet<Resource_ExperienceDetails>();
            this.Resource_Holiday = new HashSet<Resource_Holiday>();
            this.Resource_ShiftSchedule = new HashSet<Resource_ShiftSchedule>();
            this.Resource_SkillDetails = new HashSet<Resource_SkillDetails>();
            this.Resource_TimeSheet = new HashSet<Resource_TimeSheet>();
            this.Resource_WorkingPattern = new HashSet<Resource_WorkingPattern>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Sex { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<int> EthnicGroupID { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> TimeSheetFrequencyID { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public Nullable<System.DateTime> DateOfLeave { get; set; }
        public byte[] ProfilePhoto { get; set; }
        public string PhotoFileType { get; set; }
        public string NINo { get; set; }
        public Nullable<int> ImmigrationStatusID { get; set; }
        public Nullable<int> AdderessID { get; set; }
        public string Email { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string NextOfKIN_Name { get; set; }
        public string KIN_TelephoneNo { get; set; }
        public string KIN_MobileNo { get; set; }
    
        public virtual Common_Address Common_Address { get; set; }
        public virtual Common_EmployeeType Common_EmployeeType { get; set; }
        public virtual Common_EthnicGroup Common_EthnicGroup { get; set; }
        public virtual Common_ImmigrationStatus Common_ImmigrationStatus { get; set; }
        public virtual Common_MaritalStatus Common_MaritalStatus { get; set; }
        public virtual Common_Nationality Common_Nationality { get; set; }
        public virtual Common_TimeSheetFrequency Common_TimeSheetFrequency { get; set; }
        public virtual Common_Title Common_Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resouce_WorkingPatternDetails> Resouce_WorkingPatternDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_BranchDetails> Resource_BranchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_Department> Resource_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_EmployeePayment> Resource_EmployeePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_ExperienceDetails> Resource_ExperienceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_Holiday> Resource_Holiday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_ShiftSchedule> Resource_ShiftSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_SkillDetails> Resource_SkillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_TimeSheet> Resource_TimeSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_WorkingPattern> Resource_WorkingPattern { get; set; }
    }
}
