//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_TimeSheetDetails
    {
        public int TimeSheetDetailsID { get; set; }
        public Nullable<int> TimeSheetID { get; set; }
        public Nullable<int> ShiftScheduleID { get; set; }
    
        public virtual Resource_ShiftSchedule Resource_ShiftSchedule { get; set; }
        public virtual Resource_TimeSheet Resource_TimeSheet { get; set; }
    }
}
