//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_WorkingPattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_WorkingPattern()
        {
            this.Resource_WeeklyPatternDetails = new HashSet<Resource_WeeklyPatternDetails>();
        }
    
        public int PatternID { get; set; }
        public int ResourceID { get; set; }
        public Nullable<System.DateTime> PatternStartDate { get; set; }
        public Nullable<System.DateTime> PatternEndDate { get; set; }
        public Nullable<double> NoOfHours { get; set; }
    
        public virtual Resource_Employee Resource_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_WeeklyPatternDetails> Resource_WeeklyPatternDetails { get; set; }
    }
}
