//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_HolidayStatus
    {
        public int HolidayStatusID { get; set; }
        public int HolidayID { get; set; }
        public int HolidayStatusTypeID { get; set; }
        public System.DateTime StatusDateTime { get; set; }
        public string StatusChangedBy { get; set; }
        public string Comments { get; set; }
    
        public virtual Resource_Holiday Resource_Holiday { get; set; }
        public virtual Resource_HolidayStatusType Resource_HolidayStatusType { get; set; }
    }
}
