//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_WeeklyPatternDetails
    {
        public int WrkPatternDetailsID { get; set; }
        public Nullable<int> PatternID { get; set; }
        public Nullable<int> DayID { get; set; }
    
        public virtual Common_Day Common_Day { get; set; }
        public virtual Resource_WorkingPattern Resource_WorkingPattern { get; set; }
    }
}
