//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_Department()
        {
            this.Resource_DepartmentAreaDetails = new HashSet<Resource_DepartmentAreaDetails>();
        }
    
        public int ResourceDeptID { get; set; }
        public int DepartmentID { get; set; }
        public int ResourceID { get; set; }
        public int LocationID { get; set; }
        public int TeamID { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Common_Department Common_Department { get; set; }
        public virtual Common_Location Common_Location { get; set; }
        public virtual Common_Team Common_Team { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_DepartmentAreaDetails> Resource_DepartmentAreaDetails { get; set; }
    }
}
