//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_ShiftSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_ShiftSchedule()
        {
            this.Resource_TimeSheetDetails = new HashSet<Resource_TimeSheetDetails>();
        }
    
        public int ShiftScheduleID { get; set; }
        public int EmployeeID { get; set; }
        public int ShiftPatternID { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public System.DateTime ExpectedOnTime { get; set; }
        public System.DateTime ExpectedOffTime { get; set; }
        public Nullable<System.DateTime> ActualOnTime { get; set; }
        public Nullable<System.DateTime> ActualOffTime { get; set; }
        public int BranchID { get; set; }
    
        public virtual Branch_Details Branch_Details { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
        public virtual Resource_ShiftPattern Resource_ShiftPattern { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_TimeSheetDetails> Resource_TimeSheetDetails { get; set; }
    }
}
