//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resouce_WorkingPatternDetails
    {
        public int WorkingPatternID { get; set; }
        public int ResourceID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public double NoOfWorkingHours { get; set; }
        public bool Sunday { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
    
        public virtual Resource_Employee Resource_Employee { get; set; }
    }
}
