//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_SkillDetails
    {
        public int ResourceSkillID { get; set; }
        public int ResourceID { get; set; }
        public int SkillCategoryID { get; set; }
        public int SkillID { get; set; }
        public int SkillLevel { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
    
        public virtual Common_Company Common_Company { get; set; }
        public virtual Common_Skill Common_Skill { get; set; }
        public virtual Common_SkillCategory Common_SkillCategory { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
    }
}
