//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Holiday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_Holiday()
        {
            this.Resource_HolidayStatus = new HashSet<Resource_HolidayStatus>();
            this.Resource_TimeSheetDetailsHoliday = new HashSet<Resource_TimeSheetDetailsHoliday>();
        }
    
        public int HolidayID { get; set; }
        public int ResourceID { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public int HolidayTypeID { get; set; }
        public Nullable<double> BookingHrs { get; set; }
        public string Comments { get; set; }
    
        public virtual Resource_Employee Resource_Employee { get; set; }
        public virtual Resource_Holiday_Type Resource_Holiday_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_HolidayStatus> Resource_HolidayStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_TimeSheetDetailsHoliday> Resource_TimeSheetDetailsHoliday { get; set; }
    }
}
