//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_EmployeePayment
    {
        public int EmployeePayID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public int PaymentTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Common_PaymentType Common_PaymentType { get; set; }
        public virtual Resource_Employee Resource_Employee { get; set; }
    }
}
