//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_ShiftPattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource_ShiftPattern()
        {
            this.Resource_ShiftSchedule = new HashSet<Resource_ShiftSchedule>();
        }
    
        public int ShiftPatternID { get; set; }
        public string Description { get; set; }
        public int ShiftStartTime { get; set; }
        public int Duration { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> BreakDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource_ShiftSchedule> Resource_ShiftSchedule { get; set; }
    }
}
