//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_UserDetails
    {
        public int ID { get; set; }
        public string EmployeeNo { get; set; }
        public int TitleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int AddressID { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public System.DateTime JoinDate { get; set; }
        public short JobTitleID { get; set; }
        public bool Status { get; set; }
        public string StatusComment { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Common_Address Common_Address { get; set; }
        public virtual Common_JobTitle Common_JobTitle { get; set; }
        public virtual Common_Title Common_Title { get; set; }
    }
}
