//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ERP.uk.co.simplylookupadmin.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://www.simply-postcode-lookup.com/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchForAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUrlforPrefuredMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchForThoroughfareAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchForPostZonDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = Properties.Settings.Default.ERP_uk_co_simplylookupadmin_www_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchForAddressCompletedEventHandler SearchForAddressCompleted;
        
        /// <remarks/>
        public event GetAddressRecordCompletedEventHandler GetAddressRecordCompleted;
        
        /// <remarks/>
        public event GetUrlforPrefuredMapCompletedEventHandler GetUrlforPrefuredMapCompleted;
        
        /// <remarks/>
        public event SearchForThoroughfareAddressCompletedEventHandler SearchForThoroughfareAddressCompleted;
        
        /// <remarks/>
        public event SearchForPostZonDataCompletedEventHandler SearchForPostZonDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.simply-postcode-lookup.com/SearchForAddress", RequestNamespace="http://www.simply-postcode-lookup.com/", ResponseNamespace="http://www.simply-postcode-lookup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PL_AddressesDataReturnedRecord SearchForAddress(string DataKey, string Username, string SearchType, PL_SearchPrimaRecord SearchPrima) {
            object[] results = this.Invoke("SearchForAddress", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        SearchPrima});
            return ((PL_AddressesDataReturnedRecord)(results[0]));
        }
        
        /// <remarks/>
        public void SearchForAddressAsync(string DataKey, string Username, string SearchType, PL_SearchPrimaRecord SearchPrima) {
            this.SearchForAddressAsync(DataKey, Username, SearchType, SearchPrima, null);
        }
        
        /// <remarks/>
        public void SearchForAddressAsync(string DataKey, string Username, string SearchType, PL_SearchPrimaRecord SearchPrima, object userState) {
            if ((this.SearchForAddressOperationCompleted == null)) {
                this.SearchForAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchForAddressOperationCompleted);
            }
            this.InvokeAsync("SearchForAddress", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        SearchPrima}, this.SearchForAddressOperationCompleted, userState);
        }
        
        private void OnSearchForAddressOperationCompleted(object arg) {
            if ((this.SearchForAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchForAddressCompleted(this, new SearchForAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.simply-postcode-lookup.com/GetAddressRecord", RequestNamespace="http://www.simply-postcode-lookup.com/", ResponseNamespace="http://www.simply-postcode-lookup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PL_AddressRecord GetAddressRecord(string DataKey, string Username, string SearchType, string AddressID) {
            object[] results = this.Invoke("GetAddressRecord", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        AddressID});
            return ((PL_AddressRecord)(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressRecordAsync(string DataKey, string Username, string SearchType, string AddressID) {
            this.GetAddressRecordAsync(DataKey, Username, SearchType, AddressID, null);
        }
        
        /// <remarks/>
        public void GetAddressRecordAsync(string DataKey, string Username, string SearchType, string AddressID, object userState) {
            if ((this.GetAddressRecordOperationCompleted == null)) {
                this.GetAddressRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressRecordOperationCompleted);
            }
            this.InvokeAsync("GetAddressRecord", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        AddressID}, this.GetAddressRecordOperationCompleted, userState);
        }
        
        private void OnGetAddressRecordOperationCompleted(object arg) {
            if ((this.GetAddressRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressRecordCompleted(this, new GetAddressRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.simply-postcode-lookup.com/GetUrlforPrefuredMap", RequestNamespace="http://www.simply-postcode-lookup.com/", ResponseNamespace="http://www.simply-postcode-lookup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUrlforPrefuredMap(string PostCode, string ZoomLevel) {
            object[] results = this.Invoke("GetUrlforPrefuredMap", new object[] {
                        PostCode,
                        ZoomLevel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUrlforPrefuredMapAsync(string PostCode, string ZoomLevel) {
            this.GetUrlforPrefuredMapAsync(PostCode, ZoomLevel, null);
        }
        
        /// <remarks/>
        public void GetUrlforPrefuredMapAsync(string PostCode, string ZoomLevel, object userState) {
            if ((this.GetUrlforPrefuredMapOperationCompleted == null)) {
                this.GetUrlforPrefuredMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUrlforPrefuredMapOperationCompleted);
            }
            this.InvokeAsync("GetUrlforPrefuredMap", new object[] {
                        PostCode,
                        ZoomLevel}, this.GetUrlforPrefuredMapOperationCompleted, userState);
        }
        
        private void OnGetUrlforPrefuredMapOperationCompleted(object arg) {
            if ((this.GetUrlforPrefuredMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUrlforPrefuredMapCompleted(this, new GetUrlforPrefuredMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.simply-postcode-lookup.com/SearchForThoroughfareAddress", RequestNamespace="http://www.simply-postcode-lookup.com/", ResponseNamespace="http://www.simply-postcode-lookup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PL_AddressRecord SearchForThoroughfareAddress(string DataKey, string Username, string SearchType, string Postcode) {
            object[] results = this.Invoke("SearchForThoroughfareAddress", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        Postcode});
            return ((PL_AddressRecord)(results[0]));
        }
        
        /// <remarks/>
        public void SearchForThoroughfareAddressAsync(string DataKey, string Username, string SearchType, string Postcode) {
            this.SearchForThoroughfareAddressAsync(DataKey, Username, SearchType, Postcode, null);
        }
        
        /// <remarks/>
        public void SearchForThoroughfareAddressAsync(string DataKey, string Username, string SearchType, string Postcode, object userState) {
            if ((this.SearchForThoroughfareAddressOperationCompleted == null)) {
                this.SearchForThoroughfareAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchForThoroughfareAddressOperationCompleted);
            }
            this.InvokeAsync("SearchForThoroughfareAddress", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        Postcode}, this.SearchForThoroughfareAddressOperationCompleted, userState);
        }
        
        private void OnSearchForThoroughfareAddressOperationCompleted(object arg) {
            if ((this.SearchForThoroughfareAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchForThoroughfareAddressCompleted(this, new SearchForThoroughfareAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.simply-postcode-lookup.com/SearchForPostZonData", RequestNamespace="http://www.simply-postcode-lookup.com/", ResponseNamespace="http://www.simply-postcode-lookup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PL_AddressRecord SearchForPostZonData(string DataKey, string Username, string SearchType, string Postcode, string HomePostCode) {
            object[] results = this.Invoke("SearchForPostZonData", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        Postcode,
                        HomePostCode});
            return ((PL_AddressRecord)(results[0]));
        }
        
        /// <remarks/>
        public void SearchForPostZonDataAsync(string DataKey, string Username, string SearchType, string Postcode, string HomePostCode) {
            this.SearchForPostZonDataAsync(DataKey, Username, SearchType, Postcode, HomePostCode, null);
        }
        
        /// <remarks/>
        public void SearchForPostZonDataAsync(string DataKey, string Username, string SearchType, string Postcode, string HomePostCode, object userState) {
            if ((this.SearchForPostZonDataOperationCompleted == null)) {
                this.SearchForPostZonDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchForPostZonDataOperationCompleted);
            }
            this.InvokeAsync("SearchForPostZonData", new object[] {
                        DataKey,
                        Username,
                        SearchType,
                        Postcode,
                        HomePostCode}, this.SearchForPostZonDataOperationCompleted, userState);
        }
        
        private void OnSearchForPostZonDataOperationCompleted(object arg) {
            if ((this.SearchForPostZonDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchForPostZonDataCompleted(this, new SearchForPostZonDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.simply-postcode-lookup.com/")]
    public partial class PL_SearchPrimaRecord {
        
        private string organistaionField;
        
        private string buildingOrNumberField;
        
        private string streetField;
        
        private string townOrVillageField;
        
        private string countyField;
        
        private string pOBoxField;
        
        private string postcodeField;
        
        /// <remarks/>
        public string Organistaion {
            get {
                return this.organistaionField;
            }
            set {
                this.organistaionField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingOrNumber {
            get {
                return this.buildingOrNumberField;
            }
            set {
                this.buildingOrNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string TownOrVillage {
            get {
                return this.townOrVillageField;
            }
            set {
                this.townOrVillageField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string POBox {
            get {
                return this.pOBoxField;
            }
            set {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.simply-postcode-lookup.com/")]
    public partial class PL_AddressRecord {
        
        private bool addressRecordGotWithoutErrorField;
        
        private string errorMessageField;
        
        private object creditsStatusTextField;
        
        private object buyMoreCreditsURLField;
        
        private string companyNameField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string townField;
        
        private string countyStateField;
        
        private string postZipCodeField;
        
        private string countryField;
        
        private string deliveryPointSuffixField;
        
        private string noHouseHoldsField;
        
        private string smallOrgField;
        
        private string mailSortField;
        
        private string spareField;
        
        private string uDPRNField;
        
        private string uniqueField;
        
        private string longitude_WGS84Field;
        
        private string latitude_WGS84Field;
        
        private string uK_os_referenceField;
        
        private string uK_OS_grid_eastField;
        
        private string uK_OS_grid_northField;
        
        private string uK_NHS_codeField;
        
        private string uK_NHS_regionField;
        
        private string uK_countryField;
        
        private string uK_IntroductionDateField;
        
        private string uK_countyField;
        
        private string uK_districtField;
        
        private string uK_wardField;
        
        private string uK_wardstatusField;
        
        private string uK_gridstatusField;
        
        private string geoDistanceToHomePostcodeField;
        
        /// <remarks/>
        public bool AddressRecordGotWithoutError {
            get {
                return this.addressRecordGotWithoutErrorField;
            }
            set {
                this.addressRecordGotWithoutErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public object CreditsStatusText {
            get {
                return this.creditsStatusTextField;
            }
            set {
                this.creditsStatusTextField = value;
            }
        }
        
        /// <remarks/>
        public object BuyMoreCreditsURL {
            get {
                return this.buyMoreCreditsURLField;
            }
            set {
                this.buyMoreCreditsURLField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string CountyState {
            get {
                return this.countyStateField;
            }
            set {
                this.countyStateField = value;
            }
        }
        
        /// <remarks/>
        public string PostZipCode {
            get {
                return this.postZipCodeField;
            }
            set {
                this.postZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryPointSuffix {
            get {
                return this.deliveryPointSuffixField;
            }
            set {
                this.deliveryPointSuffixField = value;
            }
        }
        
        /// <remarks/>
        public string NoHouseHolds {
            get {
                return this.noHouseHoldsField;
            }
            set {
                this.noHouseHoldsField = value;
            }
        }
        
        /// <remarks/>
        public string SmallOrg {
            get {
                return this.smallOrgField;
            }
            set {
                this.smallOrgField = value;
            }
        }
        
        /// <remarks/>
        public string MailSort {
            get {
                return this.mailSortField;
            }
            set {
                this.mailSortField = value;
            }
        }
        
        /// <remarks/>
        public string Spare {
            get {
                return this.spareField;
            }
            set {
                this.spareField = value;
            }
        }
        
        /// <remarks/>
        public string UDPRN {
            get {
                return this.uDPRNField;
            }
            set {
                this.uDPRNField = value;
            }
        }
        
        /// <remarks/>
        public string Unique {
            get {
                return this.uniqueField;
            }
            set {
                this.uniqueField = value;
            }
        }
        
        /// <remarks/>
        public string longitude_WGS84 {
            get {
                return this.longitude_WGS84Field;
            }
            set {
                this.longitude_WGS84Field = value;
            }
        }
        
        /// <remarks/>
        public string latitude_WGS84 {
            get {
                return this.latitude_WGS84Field;
            }
            set {
                this.latitude_WGS84Field = value;
            }
        }
        
        /// <remarks/>
        public string UK_os_reference {
            get {
                return this.uK_os_referenceField;
            }
            set {
                this.uK_os_referenceField = value;
            }
        }
        
        /// <remarks/>
        public string UK_OS_grid_east {
            get {
                return this.uK_OS_grid_eastField;
            }
            set {
                this.uK_OS_grid_eastField = value;
            }
        }
        
        /// <remarks/>
        public string UK_OS_grid_north {
            get {
                return this.uK_OS_grid_northField;
            }
            set {
                this.uK_OS_grid_northField = value;
            }
        }
        
        /// <remarks/>
        public string UK_NHS_code {
            get {
                return this.uK_NHS_codeField;
            }
            set {
                this.uK_NHS_codeField = value;
            }
        }
        
        /// <remarks/>
        public string UK_NHS_region {
            get {
                return this.uK_NHS_regionField;
            }
            set {
                this.uK_NHS_regionField = value;
            }
        }
        
        /// <remarks/>
        public string UK_country {
            get {
                return this.uK_countryField;
            }
            set {
                this.uK_countryField = value;
            }
        }
        
        /// <remarks/>
        public string UK_IntroductionDate {
            get {
                return this.uK_IntroductionDateField;
            }
            set {
                this.uK_IntroductionDateField = value;
            }
        }
        
        /// <remarks/>
        public string UK_county {
            get {
                return this.uK_countyField;
            }
            set {
                this.uK_countyField = value;
            }
        }
        
        /// <remarks/>
        public string UK_district {
            get {
                return this.uK_districtField;
            }
            set {
                this.uK_districtField = value;
            }
        }
        
        /// <remarks/>
        public string UK_ward {
            get {
                return this.uK_wardField;
            }
            set {
                this.uK_wardField = value;
            }
        }
        
        /// <remarks/>
        public string UK_wardstatus {
            get {
                return this.uK_wardstatusField;
            }
            set {
                this.uK_wardstatusField = value;
            }
        }
        
        /// <remarks/>
        public string UK_gridstatus {
            get {
                return this.uK_gridstatusField;
            }
            set {
                this.uK_gridstatusField = value;
            }
        }
        
        /// <remarks/>
        public string GeoDistanceToHomePostcode {
            get {
                return this.geoDistanceToHomePostcodeField;
            }
            set {
                this.geoDistanceToHomePostcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.simply-postcode-lookup.com/")]
    public partial class AddressLinesClass {
        
        private string idField;
        
        private string addressField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.simply-postcode-lookup.com/")]
    public partial class PL_AddressesDataReturnedRecord {
        
        private AddressLinesClass[] linesField;
        
        private long lineCountField;
        
        private bool searchPerformedWithoutErrorField;
        
        private string errorMessageField;
        
        private string buyMoreCreditsURLField;
        
        private string creditsStatusTextField;
        
        private long creditsLeftField;
        
        /// <remarks/>
        public AddressLinesClass[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
            }
        }
        
        /// <remarks/>
        public long LineCount {
            get {
                return this.lineCountField;
            }
            set {
                this.lineCountField = value;
            }
        }
        
        /// <remarks/>
        public bool SearchPerformedWithoutError {
            get {
                return this.searchPerformedWithoutErrorField;
            }
            set {
                this.searchPerformedWithoutErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string BuyMoreCreditsURL {
            get {
                return this.buyMoreCreditsURLField;
            }
            set {
                this.buyMoreCreditsURLField = value;
            }
        }
        
        /// <remarks/>
        public string CreditsStatusText {
            get {
                return this.creditsStatusTextField;
            }
            set {
                this.creditsStatusTextField = value;
            }
        }
        
        /// <remarks/>
        public long CreditsLeft {
            get {
                return this.creditsLeftField;
            }
            set {
                this.creditsLeftField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SearchForAddressCompletedEventHandler(object sender, SearchForAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchForAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchForAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PL_AddressesDataReturnedRecord Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PL_AddressesDataReturnedRecord)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAddressRecordCompletedEventHandler(object sender, GetAddressRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PL_AddressRecord Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PL_AddressRecord)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUrlforPrefuredMapCompletedEventHandler(object sender, GetUrlforPrefuredMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUrlforPrefuredMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUrlforPrefuredMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SearchForThoroughfareAddressCompletedEventHandler(object sender, SearchForThoroughfareAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchForThoroughfareAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchForThoroughfareAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PL_AddressRecord Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PL_AddressRecord)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SearchForPostZonDataCompletedEventHandler(object sender, SearchForPostZonDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchForPostZonDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchForPostZonDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PL_AddressRecord Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PL_AddressRecord)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591